name: Deploy stories

on:
  push:
    branches:
      - master

jobs:
  deploy_stories:
    name: Deploy stories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build stories
        run: yarn storybook:build

      - name: Deploy stories
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: dist
          fqdn: ng-monaco-editor.js.org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
